export default function BlogExample1() {
    return (
        <div className="flex flex-col">
            <h1 className="text-3xl md:text-6xl">Blog 1 Title</h1>
            <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus varius a ligula vitae lacinia. Mauris hendrerit nisl vitae dolor ultrices aliquet. Sed leo nisl, finibus lacinia ultrices id, aliquam at eros. Cras pellentesque finibus suscipit. Aliquam ut egestas libero. Fusce suscipit velit vitae velit mollis semper. Mauris ante sapien, faucibus et odio id, ultricies sagittis dolor. Aliquam leo tortor, fringilla nec convallis id, luctus a eros. Quisque velit lacus, rhoncus id dictum vitae, posuere sit amet dolor. Phasellus at metus in lacus tempus mattis. Proin ut tortor sit amet ex bibendum sagittis quis a velit. Fusce iaculis dui eget porttitor pulvinar. Cras in convallis elit. Pellentesque pretium feugiat eleifend. Integer dignissim dapibus leo, eu placerat purus condimentum non. Quisque auctor porta mauris volutpat dapibus.

                Nunc rutrum, lectus sit amet viverra facilisis, sem mauris molestie purus, quis scelerisque lectus lorem at augue. Mauris gravida hendrerit augue, ut eleifend nunc ornare non. Aenean vitae imperdiet orci. Suspendisse quis risus auctor, rutrum diam rutrum, posuere dui. Morbi porttitor leo non laoreet scelerisque. Nunc libero lectus, congue id metus porttitor, rhoncus luctus nibh. Phasellus semper congue eros, vitae egestas erat imperdiet ac. Duis nec felis lobortis, egestas augue ac, laoreet erat.

                Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nulla tristique tempor augue, eget suscipit massa consequat vitae. Curabitur aliquet efficitur urna ac fringilla. Duis feugiat scelerisque est, et semper ipsum tincidunt nec. Aenean molestie, lectus sit amet commodo venenatis, felis diam tincidunt nisl, eu placerat metus tortor vel arcu. Maecenas nibh neque, eleifend vel lacus non, ultrices aliquet eros. Ut sed dignissim urna, nec pulvinar metus. Nam scelerisque, nibh suscipit vestibulum efficitur, elit risus vestibulum tellus, in dictum quam sapien ac nibh. Nunc magna neque, pulvinar ut arcu non, pretium eleifend massa. Morbi posuere, quam in feugiat bibendum, nisl mi convallis mauris, eu tempor nisl nibh ut urna. In nec accumsan nulla, id rhoncus metus. Phasellus vulputate maximus mauris, eget malesuada sapien dignissim a. Donec pellentesque suscipit lorem, ac pharetra nisl consequat eget.

                In tincidunt neque est, ut laoreet enim commodo eget. Phasellus lacus arcu, laoreet ut accumsan suscipit, feugiat non purus. Nunc massa lectus, lobortis a pellentesque in, posuere nec tellus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aliquam tempus ac velit sit amet fringilla. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed consectetur at velit eu interdum. Praesent dapibus tincidunt leo in pretium. Quisque vestibulum mauris enim, vel gravida libero tincidunt quis.

                Sed sed lectus eu risus placerat laoreet non sit amet metus. Ut dapibus leo vel suscipit pretium. Nam elementum condimentum enim, sit amet faucibus nibh elementum vitae. Fusce commodo commodo ex, vel ultricies mi blandit et. Quisque ut posuere mi. Donec ipsum mauris, condimentum at felis sed, tristique laoreet nunc. Aliquam suscipit dolor non dapibus sagittis. Vivamus purus magna, tristique at consequat sit amet, consequat sed turpis. Quisque pharetra quam non arcu aliquam, quis congue felis auctor.

                Cras nisi velit, pretium in ullamcorper quis, rutrum sit amet mauris. Fusce ut ipsum eu diam luctus lobortis. Sed dapibus placerat pretium. Vestibulum placerat ligula nibh, ac pulvinar turpis finibus id. Praesent sed nisl risus. Nam ullamcorper maximus luctus. Vivamus sed sapien enim. Ut a turpis at leo porttitor dapibus vitae non magna. Suspendisse potenti. Curabitur non eleifend lacus, eu porttitor tellus. Proin purus libero, blandit eu quam ac, posuere gravida velit. Cras quis elit sollicitudin, consectetur ex vitae, ullamcorper lectus. Nunc quis ligula semper, egestas risus blandit, ultrices turpis. Mauris ornare orci non magna tempor commodo.
            </p>
        </div>
    );
}